### ISSUE TITLE
pathway-commons-transform not in dockerhub?

### ISSUE THREAD

**Issue by prismofeverything** [biostream/pathway-commons-transform#4]
I get this error when trying to run the pathway commons transform:

```
Unable to find image 'biostream/pathway-commons-transform:latest' locally
Pulling repository docker.io/biostream/pathway-commons-transform
docker: Tag latest not found in repository docker.io/biostream/pathway-commons-transform.
See 'docker run --help'.
```

**Comment by kellrott** [comment]
Looks like it was entered, but the auto build was never triggered. I've triggered it manually, and it should be read in a few minutes.

**Comment by adamstruck** [comment]
My PR that included that dockerfile was never merged. 

https://github.com/biostream/pathway-commons-transform/pull/3

**Comment by prismofeverything** [comment]
Now merged.
